import Layout from "@/layout";
import Head from "next/head";
import Image from "next/image";
// import styles from "@/styles/Home.module.css";

const Home = () => {
  return (
    <>
      <Head>
        <title>بهار پودولوژی</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <span>Hello</span>
      </Layout>
    </>
  );
};

export default Home;
